%% DECISION VARIABLES
syms Corn ...
     Cotton ...
     Apples ...
     Oranges ...
     Melons ...
     Almonds ...
     Pecans ...
     Hazelnuts ...
     Pistachios ...
     Rice ...
     Soybeans ...
     Flax ...
     Sugarcane ...
     Beans ...
     Peas ...
     % Variables represent acres of crop to plant
%% Equations
vars = [Corn, Cotton, Apples, Oranges, Melons, Almonds, Pecans, Hazelnuts,...
        Pistachios, Rice, Soybeans, Flax, Sugarcane, Beans, Peas];

    
clear eqns
%nonnegativity
eqns = [sum(vars) == 1000];
for i = 1 : size(vars,2)
    eqns(end+1) = (-vars(i) == 0)w;
end